CREATE TABLE authors (
  id int GENERATED BY DEFAULT AS IDENTITY,
  first_name varchar(100),
  last_name varchar(100),
  PRIMARY KEY (id)
);

CREATE TABLE genres (
  id int GENERATED BY DEFAULT AS IDENTITY,
  name varchar(100),
  PRIMARY KEY (id)
);

CREATE TABLE games (
  id int GENERATED BY DEFAULT AS IDENTITY,
  genre int REFERENCES genres(id),
  author int REFERENCES authors(id),
  label int REFERENCES labels(id),
  publish_date date,
  multiplayer varchar(100),
  last_played_at date,
  archived boolean,
  PRIMARY KEY (id)
);

CREATE TABLE music_album (
  id int GENERATED BY DEFAULT AS IDENTITY,
  genre int REFERENCES genres(id),
  author int REFERENCES authors(id),
  label int REFERENCES labels(id),
  publish_date date,
  on_spotify boolean,
  archived boolean,
  PRIMARY KEY (id)
);
